In [2]:
import numpy as np

### 1. Numpy Basics (각 1점씩)

(1) 다음과 같은 3차원의 array가 있다고 합시다.  
기존의 형태를 유지하면서 10보다 크거나 같은 값들을 0으로 바꾸는 코드를 작성해봅시다

In [3]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [6]:
np.where(c >= 10, 0, c)

array([[[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

(2) 아래의 6 by 4 Array를 가로축(행)과 세로축(열)에 대해서 더한(sum) 새로운 array 2개를 만들어 보시오  

In [7]:
arr=np.arange(24).reshape(6,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [8]:
arr.sum(axis=0)

array([60, 66, 72, 78])

In [9]:
arr.sum(axis=1)

array([ 6, 22, 38, 54, 70, 86])

### 2. Random walks (각 1점씩)

(1) 주사위를 던져서 1,2,3이 나오면 뒤로 한칸 가고, 4,5,6이 나오면 앞으로 한칸 가는 Random walkers를 100명 만들어보세요.  
각각의 Random walker는 주사위를 총 500번씩 던집니다.  

In [ ]:
dice = np.random.randint(1,7)
nwalks = 100 # 랜덤 워크 시뮬레이션을 수행할 워크(걷기)의 수입니다. 이 예시에서는 5000개의 워크가 생성됩니다.
nsteps = 500 # 한 워크에서 수행할 총 단계 수입니다. 각 워크는 이 총 단계 수에 따라 이동합니다. 이 예시에서는 1000단계로 설정되어 있습니다.
draws = rng.integers(0, 2, size=(nwalks, nsteps)) # rng.integers(0, 2, size=(nwalks, nsteps))를 통해 0과 1 사이의 정수를 무작위로 생성한 배열입니다. 
                                                    # 이 배열은 nwalks 행과 nsteps 열을 가지며, 각 워크에서 각 단계마다 무작위로 0 또는 1이 선택됩니다.
steps = np.where(draws > 0, 1, -1) # np.where(draws > 0, 1, -1)를 사용하여 draws 배열의 각 요소가 0보다 큰 경우 1을, 그렇지 않은 경우 -1을 가지는 배열을 생성합니다. 
                                    # 이 배열은 draws 배열과 같은 크기를 가지며, 각 단계에서의 이동 방향을 나타냅니다. 
                                    # 0보다 큰 경우에는 1이 선택되어 오른쪽으로 이동하고, 0인 경우에는 -1이 선택되어 왼쪽으로 이동합니다.
walks = steps.cumsum(axis=1) # steps.cumsum(axis=1)를 통해 steps 배열을 누적 합(cumulative sum)하여 워크의 위치를 나타내는 배열을 생성합니다. 
                                # axis=1은 각 행에 대해 누적 합을 계산함을 의미합니다. 
                                # 이로써 walks 배열은 nwalks 행과 nsteps 열을 가지며, 각 워크의 각 단계에서의 위치를 나타냅니다.

In [2]:
import random

num_walkers = 100
num_steps = 500

# 각 Walker의 초기 위치는 0으로 설정
walkers = [0] * num_walkers

for _ in range(num_steps):
    for i in range(num_walkers):
        # 주사위 던지기
        dice_roll = random.randint(1, 6)
        
        # 주사위 결과에 따라 위치 업데이트
        if dice_roll <= 3:
            walkers[i] -= 1  # 1, 2, 3이 나오면 뒤로 한칸
        else:
            walkers[i] += 1  # 4, 5, 6이 나오면 앞으로 한칸

walkers
# 결과 출력
#for i in range(num_walkers):
#    print(f"Walker {i + 1}: {walkers[i]}")


[50,
 -28,
 -6,
 -8,
 -2,
 2,
 -30,
 0,
 20,
 -38,
 -12,
 -18,
 14,
 12,
 -12,
 8,
 -2,
 4,
 18,
 -4,
 26,
 20,
 10,
 40,
 -14,
 -12,
 -4,
 -10,
 2,
 46,
 24,
 4,
 -20,
 14,
 32,
 4,
 40,
 16,
 -34,
 4,
 -8,
 -20,
 14,
 -34,
 -56,
 -52,
 -8,
 32,
 22,
 22,
 20,
 20,
 -10,
 20,
 -12,
 -6,
 32,
 2,
 12,
 2,
 -20,
 0,
 22,
 -8,
 12,
 -10,
 14,
 14,
 -20,
 6,
 -16,
 -34,
 -16,
 -28,
 0,
 -8,
 -20,
 -2,
 0,
 18,
 -32,
 6,
 -38,
 -20,
 42,
 24,
 28,
 -10,
 -18,
 -36,
 -50,
 -32,
 46,
 -2,
 -30,
 20,
 -44,
 -2,
 12,
 -8]

In [23]:
import numpy as np

num_walkers = 100
num_steps = 500

# 주사위를 500번 던져 나오는 결과를 한 번에 생성합니다.
dice_rolls = np.random.randint(1, 7, size=(num_walkers, num_steps))

# 주사위 결과에 따라 이동 방향을 결정하고 누적 이동 거리를 계산합니다.
positions = np.where(dice_rolls <= 3, -1, 1)
cumulative_positions = np.cumsum(positions, axis=1)

# 각 Random walker의 최종 위치를 출력합니다.
#cumulative_positions
for i in range(num_walkers):
    final_position = cumulative_positions[i, -1]
    print(f"Walker {i+1}: Final position = {final_position}")


Walker 1: Final position = -6
Walker 2: Final position = -30
Walker 3: Final position = 32
Walker 4: Final position = -54
Walker 5: Final position = -24
Walker 6: Final position = -22
Walker 7: Final position = -24
Walker 8: Final position = 2
Walker 9: Final position = 22
Walker 10: Final position = -20
Walker 11: Final position = -16
Walker 12: Final position = 6
Walker 13: Final position = 0
Walker 14: Final position = 8
Walker 15: Final position = 32
Walker 16: Final position = 2
Walker 17: Final position = 6
Walker 18: Final position = -36
Walker 19: Final position = -12
Walker 20: Final position = 22
Walker 21: Final position = 4
Walker 22: Final position = -36
Walker 23: Final position = 2
Walker 24: Final position = 16
Walker 25: Final position = 4
Walker 26: Final position = 8
Walker 27: Final position = -8
Walker 28: Final position = 14
Walker 29: Final position = -4
Walker 30: Final position = -26
Walker 31: Final position = 16
Walker 32: Final position = -4
Walker 33: Final

In [20]:
import random

#random_walkers = []

for i in range(100):
    random_walker = [0]
    for j in range(500):
        roll = random.randint(1, 6)
        if roll <= 3:
            random_walker.append(random_walker[-1] - 1)
        else:
            random_walker.append(random_walker[-1] + 1)
    random_walkers.append(random_walker)

random_walkers


AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [18]:
import numpy as np

nwalkers = 100  # 랜덤 워커의 수
nsteps = 500  # 주사위를 던지는 횟수


# 랜덤 워커의 위치를 저장할 배열 생성
walkers = np.zeros((nwalkers, nsteps+1), dtype=int)

for i in range(nsteps):
    # 주사위 던지기
    dice = np.random.randint(1,7, size=nwalkers)
    
    # 1, 2, 3이 나오면 뒤로 한 칸 가기 (음수 방향)
    walkers[:, i+1] = walkers[:, i] - np.where(dice <= 3, 1, 0)
    
    # 4, 5, 6이 나오면 앞으로 한 칸 가기 (양수 방향)
    walkers[:, i+1] = walkers[:, i] + np.where(dice >= 4, 1, 0)

#결과 출력
for j in range(nwalkers):
    print(f"Walker {j+1}: {walkers[j]}")


Walker 1: [  0   1   1   2   3   3   3   3   3   4   4   5   5   6   6   7   8   8
   9  10  10  10  11  12  13  14  15  15  16  17  18  19  20  20  20  20
  21  21  21  22  23  24  25  26  26  27  27  27  27  28  29  30  31  31
  31  32  32  33  33  33  33  34  35  35  35  35  35  36  37  37  38  38
  39  40  41  42  43  44  45  46  47  48  49  49  50  50  51  51  51  52
  52  52  53  54  54  54  54  55  55  55  55  56  57  58  58  59  59  59
  59  60  60  61  62  63  63  64  64  64  65  66  66  66  66  67  67  67
  68  69  69  70  70  70  71  71  71  72  73  74  75  75  76  76  77  78
  79  79  79  79  79  79  80  80  80  81  81  81  81  81  81  82  83  84
  85  86  87  87  88  88  89  90  91  92  93  94  95  96  97  97  98  99
  99  99 100 101 102 102 103 104 104 104 105 105 106 106 107 107 107 107
 108 108 109 110 110 111 112 113 113 114 114 115 116 116 116 117 118 119
 119 119 120 120 121 122 122 122 123 124 125 126 126 127 127 128 128 129
 129 130 131 132 133 134 134 134 135 135 

***

In [15]:
import numpy as np
import matplotlib.pyplot as plt

random_walkers = np.zeros((100, 500))

for i in range(100):
    for j in range(500):
        roll = np.random.randint(1, 7)
        if roll <= 3:
            random_walkers[i, j] = random_walkers[i, j - 1] - 1
        else:
            random_walkers[i, j] = random_walkers[i, j - 1] + 1

random_walkers

for j in range(random_walkers):
    print(f"Walker {j+1}: {walkers[j]}")



array([[ -1.,  -2.,  -1., ...,   6.,   5.,   6.],
       [ -1.,  -2.,  -1., ...,   2.,   3.,   4.],
       [ -1.,   0.,   1., ...,  16.,  17.,  16.],
       ...,
       [ -1.,   0.,  -1., ..., -16., -15., -16.],
       [ -1.,  -2.,  -1., ..., -12., -11., -10.],
       [  1.,   0.,  -1., ..., -24., -25., -24.]])

In [20]:
walkers[:, i+1] = walkers[:, i] - np.where(dice <= 3, 1, 0)
    

array([231, 246, 237, 248, 243, 245, 246, 243, 252, 270, 248, 249, 268,
       244, 262, 241, 267, 253, 256, 248, 248, 262, 236, 249, 271, 253,
       235, 239, 262, 251, 227, 259, 254, 256, 246, 246, 253, 248, 263,
       254, 261, 250, 252, 267, 268, 245, 259, 244, 268, 247, 252, 256,
       256, 237, 230, 247, 265, 239, 264, 241, 228, 253, 263, 242, 252,
       267, 242, 261, 259, 256, 238, 253, 224, 232, 249, 251, 234, 262,
       251, 253, 239, 256, 243, 231, 250, 256, 246, 254, 245, 257, 257,
       245, 237, 261, 251, 259, 260, 254, 248, 263])

(2) 위에서 도출한 Random walkers 중, 가장 앞으로 많이 간 Walker와 뒤로 가장 많이 간 Walker의 step을 각각 출력하시오

In [9]:
max_step = max(random_walkers)
max_step

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [16]:
walkers.min()

0

(3) 원점에서부터 +-50만큼 떨어진 거리에 도달한 Walker는 총 몇명입니까?