In [1]:
import numpy as np

### 1. Numpy Basics (각 1점씩)

(1) 다음과 같은 3차원의 array가 있다고 합시다.  
기존의 형태를 유지하면서 10보다 크거나 같은 값들을 0으로 바꾸는 코드를 작성해봅시다

In [2]:
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [7]:
np.where(c >= 10, 0, c)

array([[[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

(2) 아래의 6 by 4 Array를 가로축(행)과 세로축(열)에 대해서 더한(sum) 새로운 array 2개를 만들어 보시오  

In [4]:
arr=np.arange(24).reshape(6,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
arr.sum(axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [6]:
arr.sum(axis=0)

array([60, 66, 72, 78])

### 2. Random walks (각 1점씩)

(1) 주사위를 던져서 1,2,3이 나오면 뒤로 한칸 가고, 4,5,6이 나오면 앞으로 한칸 가는 Random walkers를 100명 만들어보세요.  
각각의 Random walker는 주사위를 총 500번씩 던집니다.  

In [ ]:
arr = np.random.randn(100)


(2) 위에서 도출한 Random walkers 중, 가장 앞으로 많이 간 Walker와 뒤로 가장 많이 간 Walker의 step을 각각 출력하시오

(3) 원점에서부터 +-50만큼 떨어진 거리에 도달한 Walker는 총 몇명입니까?