In [1]:
import numpy as np

## 1. (각 3점)

(1) 다음과 같은 List가 있다고 할 때 해당 List의 끝에 60이란 숫자를 추가하시오

In [2]:
a = [10, 20, 30, 40, 50]
a

[10, 20, 30, 40, 50]

In [3]:
a.append(60)
a

[10, 20, 30, 40, 50, 60]

(2) 다음과 같은 lista가 있다고 할 때 숫자 10 전의 모든 합을 계산하는 코드를 작성하시오

In [10]:
sequence = [1, 2, 0, 4, 6, 5, 2, 1, 10, 15, 7, 100]

In [11]:
total_until_10 = 0
for value in sequence:
    if value == 10:
        break
    total_until_10 += value

In [12]:
total_until_10

21

## 2. (3점)

다음과 같은 사람의 이름(cast)과 이 사람의 키(heights)를 나타내는 List가 있다고 할 때, 앞 글자가 B로 시작하는 사람의 키(heights)를 이름을 Key로 하고 키(heights)값을 value로 하는 dictionary로 추출하는 코드를 작성히시오

In [13]:
cast = ["Barney Stinson", "Robin Scherbatsky", "Ted Mosby", "Lily Aldrin", "Marshall Eriksen", "Bob"]
heights = [72, 68, 72, 66, 76, 80]

In [14]:
height_start_B = {}

In [15]:
for idx, x in enumerate(cast):
    if x[0] == 'B':
        height_start_B[x] = heights[idx]

In [16]:
height_start_B

{'Barney Stinson': 72, 'Bob': 80}

## 3. (3점)
아래 `sequence` object의 합을 계산하는 코드를 작성하시오

In [17]:
sequence = [1, 2, None, 4, None, 5, 6, 8, 9, 10]

In [18]:
total = 0

for value in sequence:
    if value is None:
        continue
    total += value

total

45

## 4. (3점)
다음과 같은 농구선수의 나이와 키를 담은 dictionary가 주어질 때 아래 물음에 답하시오


In [19]:
basket = {'Paul':[36, 183], 'James': [37, 206], 'Durant': [33, 208], 'Trae': [23, 185], 'Harden': [32, 196]}

키가 200 이상이면서 나이가 35세 이하인 선수의 이름을 추출하는 코드를 작성하시오

In [22]:
for name in basket:
    print(name)

Paul
James
Durant
Trae
Harden


In [20]:
player = []
for name in basket:
    mask = (basket[name][0] <= 35) & (basket[name][1] >= 200)
    if mask:
        player.append(name)

In [21]:
player

['Durant']

## 5. Dictionary (3점)
다음과 같은 list가 있다고 했을 때 이 List를 dictionary 형태로 변환해 보시오

출력결과물

```python
{0: 'apple', 1: 'banana', 2: 'grapes', 3: 'pear'}
```

In [23]:
my_list = ['apple', 'banana', 'grapes', 'pear']

In [ ]:
num = [0,1,2,3,4]
dict

In [24]:
new_dict = {}
for i, j in enumerate(my_list):
    new_dict[i] = j

new_dict

{0: 'apple', 1: 'banana', 2: 'grapes', 3: 'pear'}

## 6. Numpy - 각 3점씩

1) 0에서부터 29까지의 숫자가 순서대로 들어간 3x10 matrix를 만들어 보시오. 최종 결과물은 아래와 같습니다 

In [29]:
arr = np.arange(30).reshape((3, 10))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

2) 1)에서 생성한 array의 모든 element에 10을 곱한 후 5를 더한 새로운 array를 생성히시오

In [30]:
arr * 10 + 5

array([[  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [105, 115, 125, 135, 145, 155, 165, 175, 185, 195],
       [205, 215, 225, 235, 245, 255, 265, 275, 285, 295]])

3) 1)에서 생성한 array에서 10보다 크거나 같은 모든 원소들을 999로 변환하는 코드를 작성하시오


In [31]:
arr[arr >= 10] = 999
arr

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999, 999, 999, 999, 999, 999]])

4) 1) 에서 생성한 array에서 20보다 크거나 같은 값들만 7을 빼주는 코드를 작성하시오

In [32]:
arr = np.arange(30).reshape((3, 10))

In [33]:
arr[arr >= 20] = arr[arr >= 20] - 7
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22]])